name: Deploy to VPS

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_USER: ${{ secrets.REMOTE_USER }}
  REMOTE_PATH: ${{ secrets.REMOTE_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io docker-compose

      - name: Build and push Docker image
        run: |
          docker build -t backend_web .
          docker tag backend_web:latest backend_web:$(git rev-parse --short HEAD)
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push my_django_project:latest
          docker push my_django_project:$(git rev-parse --short HEAD)

      - name: Upload code to VPS
        uses: SamKirkland/FTP-Deploy-Action@4.1.1
        with:
          server: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_dir: ./
          remote_dir: ${{ env.REMOTE_PATH }}

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.19.2
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.REMOTE_PATH }}
            docker-compose up -d
