name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose sshpass
    - name: Build and push Docker image
      run: |
        docker build -t my_django_project .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag my_django_project $DOCKER_USERNAME/my_django_project:latest
        docker push $DOCKER_USERNAME/my_django_project:latest
    - name: SSH Deploy
      uses: easingthemes/ssh-deploy@v2.2.3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        source: ./docker-compose.yml
        target: /home/user/docker-compose.yml
        script: |
          cd /home/user/
          docker-compose pull
          docker-compose up -d
