name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh-client

      - name: Setup SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key && chmod 600 ssh_key && ssh-add ssh_key

      - name: Copy Docker Compose file to VPS
        uses: appleboy/scp-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: /home/user/my_django_project/docker-compose.yml

      - name: Copy code to VPS
        uses: appleboy/scp-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /home/user/my_django_project

      - name: SSH into VPS and start Docker Compose
        uses: appleboy/ssh-action@v0.18.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user/my_django_project
            docker-compose up -d
